DanceCon/DanceCon/Controllers/AcountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DanceCon.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DanceCon.Controllers
{
    public class AcountController : Controller
    {
        protected UserManager<IdentityUser> UserManager { get; }

        protected SignInManager<IdentityUser> SignInManager { get; }

        public AcountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            SignInManager = signInManager;
            UserManager = userManager;
        }
        [HttpGet]
        public async Task<IActionResult> Register()
        {
            return View();


        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser(viewModel.Login) { Email = viewModel.Email };
                var result = await UserManager.CreateAsync(user, viewModel.Password);

                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false);
                     await UserManager.AddToRoleAsync(user, "User");

                    return RedirectToAction("Index", "Home");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Login()
        {
            return View();


        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = await SignInManager.PasswordSignInAsync(viewModel.Login,
                                        viewModel.Password, false, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                
                    ModelState.AddModelError(string.Empty, "Nie można się zalogować!");
               
            }
            return View(viewModel);
        }
        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await SignInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

DanceCon/DanceCon/Controllers/ContestController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using DanceCon.Context;
using DanceCon.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace DanceCon.Controllers
{
    public class ContestController : Controller
    {
        private readonly IHostingEnvironment hostingEnvironment;
        protected UserManager<IdentityUser> UserManager { get; }
        protected SignInManager<IdentityUser> SignInManager { get; }
        public ContestController(IHostingEnvironment hostingEnvironment, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this.hostingEnvironment = hostingEnvironment;
            SignInManager = signInManager;
            UserManager = userManager;
        }

        
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Contestlist(string sortOrder)
        {
            var context = new EFCContext();

            List<ContestViewModel> pm = new List<ContestViewModel> { };
            var con = from c in context.Contests select c;

            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.CountrySortParm = String.IsNullOrEmpty(sortOrder) ? "country_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            switch (sortOrder)
            {
                case "title_desc":
                    con = con.OrderBy(c => c.Title);
                    break;
                case "country_desc":
                    con = con.OrderBy(c => c.Country);
                    break;
                case "Date":
                    con = con.OrderBy(c => c.ContestDate);
                    break;
                case "date_desc":
                    con = con.OrderByDescending(c => c.ContestDate);
                    break;
                default:
                    con = con.OrderBy(c => c.ContestDate);
                    break;
            }

            return View("Contestlist", con.ToList()); 
        }

        [HttpGet]
        public IActionResult UserEvent(string sortOrder)
        {
            var context = new EFCContext();
            var userID = "";
            if (User.Identity.IsAuthenticated)
            {
                userID = UserManager.GetUserId(User);
            }
     
            List<ContestViewModel> pm = new List<ContestViewModel> { };
            var con = from c in context.Contests select c;

            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.CountrySortParm = String.IsNullOrEmpty(sortOrder) ? "country_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            switch (sortOrder)
            {
                case "title_desc":
                    con = con.OrderBy(c => c.Title);
                    break;
                case "country_desc":
                    con = con.OrderBy(c => c.Country);
                    break;
                case "Date":
                    con = con.OrderBy(c => c.ContestDate);
                    break;
                case "date_desc":
                    con = con.OrderByDescending(c => c.ContestDate);
                    break;
                default:
                    con = con.OrderBy(c => c.ContestDate);
                    break;
            }

            var usercontest = con.Where(x => x._UserID == userID).ToList();
            return View("UserEvent", usercontest);

        }

        [HttpGet]
        public IActionResult UserPart(string sortOrder)
        {
            var context = new EFCContext();
            var userID = "";
            if (User.Identity.IsAuthenticated)
            {
                userID = UserManager.GetUserId(User);
            }

            List<ContestViewModel> pm = new List<ContestViewModel> { };
            var con = from c in context.Contests select c;


            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.CountrySortParm = String.IsNullOrEmpty(sortOrder) ? "country_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            switch (sortOrder)
            {
                case "title_desc":
                    con = con.OrderBy(c => c.Title);
                    break;
                case "country_desc":
                    con = con.OrderBy(c => c.Country);
                    break;
                case "Date":
                    con = con.OrderBy(c => c.ContestDate);
                    break;
                case "date_desc":
                    con = con.OrderByDescending(c => c.ContestDate);
                    break;
                default:
                    con = con.OrderBy(c => c.ContestDate);
                    break;
            }
            var userparticipant = context.Participants.Where(x => x._UserID == userID).ToList();
            var contestID = 0;
            ContestViewModel ct;
            foreach (var part in userparticipant)
            {
                contestID = part._ContestID;
                ct = con.Single(x => x.ID == contestID);
                pm.Add(ct);
            }
            return View("UserPart", pm);

        }
        
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Participants(int id, [FromServices] EFCContext context)
        {
            var CM = new ContestManger();

            var participant = CM.GetParticipants(id);
            return View("Participants", participant);
        }
       
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public IActionResult Add(ContestModel contest,[FromServices] EFCContext context)
        {
            if(context.Contests.Any(x=> x.Title == contest.Title))
            {

                ModelState.AddModelError("Title", "Contest with this title exist");
                return View();
            }
            else if(contest.ContestDate < DateTime.Now)
            {

                ModelState.AddModelError("ContestDate", "NO PAST CONTEST");
                return View();

            }
            if (ModelState.IsValid)
            {
                var userIdValue = "";
                var claimsIdentity = User.Identity as ClaimsIdentity;
                if (claimsIdentity != null)
                {
                   
                    var userIdClaim = claimsIdentity.Claims
                        .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                    if (userIdClaim != null)
                    {
                        userIdValue = userIdClaim.Value;
                    }
                }

                string uniqueFileName = null;
                if (contest.Photo != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + contest.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    contest.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                var pm = new ContestManger();
                var contestModel = new ContestViewModel
                {

                    Title = contest.Title,
                    Country = contest.Country,
                    City = contest.City,
                    Categories = contest.Categories,
                    //Judges = contest.Judges,
                    Type = contest.Type,
                    Description = contest.Description,
                    ContestDate = contest.ContestDate,
                    AddedDate = DateTime.Now,
                    _UserID = userIdValue,
                    PhotoPath = uniqueFileName

                };


                pm.AddContest(contestModel);
                /*   foreach (var j in contest.Judges)
                   {
                       var judgesmodel = new Judge
                       {
                           _JudgeName = j.ToString(),


                       };
                       pm.AddJudge(judgesmodel);
                   }
                   */


                ViewData["Massage"] = contestModel;
                
                return View("AddJudge");
            }
            return View();
        }
        [HttpGet]
        public IActionResult AddJudge()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddJudge(IFormCollection fc, [FromServices] EFCContext context)
        {
            string test = fc["texttest"];
            var judge = test.Split(",");
            var pm = new ContestManger();
            var cust = context.Contests.Last() ;

            int id = cust.ID;
            
            foreach (var j in judge)
            { var judgemodel = new Judge
            {

                _JudgeName = j,
                _ContestID = id
              

            };
            pm.AddJudge(judgemodel); }


            return RedirectToAction("Details");
        }
        [HttpGet]
        public IActionResult Details([FromServices] EFCContext context)
        {
          
            var cust = context.Contests.Last();
            DetailViewModel mymodel = new DetailViewModel();
            mymodel.Contests = context.Contests.Single(x => x.ID == cust.ID);

DanceCon/DanceCon/Views/Shared/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManger;
@model DanceCon.Models.ContestViewModel
@{
    ViewData["Title"] = "Home Page";
    var photoPath = "~/images/" + (Model.PhotoPath ?? "noimage.png");
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="item active">
            <div class="row">
                <div class="col-xs-4">
                    <img src="~/images/" class="img-responsive" />
                    <div class="carousel-caption">
                        <h3></h3>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/74835935_3250438711694424_2921376337434247168_o.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>




</div>

<div>
    @if (signInManger.IsSignedIn(User))
    {
        <div>Użytkownik Zalogowany.</div>
        <a href="/Acount/LogOut">Wyloguj  @User.Identity.Name</a>
        <a href="/Role"> ROLE</a>
    }
    else
    {
        <div>Użytkownik Niezalogowany.</div>
        <a href="/Acount/LogIn">Zaloguj</a>
    }
    <a href="/Acount/Register">Rejestracja</a>
    <a href="/Role"> ROLE</a>
</div>

DanceCon/DanceCon/Views/Shared/NotFound.cshtml
@{ 
    ViewBag.Title = "not found";
}

<h1>@ViewBag.ErrorMessage</h1>
<a asp-action="index" asp-controller="home">Click here to navigate to HOME PAGE</a>

DanceCon/DanceCon/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManger;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contest Advisor</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
       
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-primary">
        <div class="container">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Contest Advisor</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse show" id="navbarColor01" style="">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home<span class="sr-only">(current)</span></a></li>
                    <li class="nav-item active"><a class="nav-link" asp-area="" asp-controller="Contest" asp-action="Contestlist">Contests</a></li>
                    @if (signInManger.IsSignedIn(User))
                    {
                        <li class="nav-item active"> <a href="~/Contest/Add" class="nav-link">Add Contest</a></li>
                        <li class="nav-item active"><a href="~/Contest/UserEvent" class="nav-link">Your Contest</a></li>
                        <li class="nav-item active"><a href="~/Contest/UserPart" class="nav-link">Participer</a></li>

                    }
                    @if(User.IsInRole("Admin"))
                    {
                        <li class="nav-item active"><a href="~/Role" class="nav-link">Roles</a></li>


                    }

                </ul>
                <ul class="navbar-nav justify-content-end" id="navbarColor02">
                    @if (signInManger.IsSignedIn(User))
                    {
                        
                        <li class="nav-item active"><a href="~/Acount/LogOut" class="nav-link">Wyloguj  @User.Identity.Name</a></li>

                    }
                   
                    else
                    {

                        <li class="nav-item active"><a class="nav-link" asp-area="" asp-controller="Acount" asp-action="Register">Register</a></li>
                        <li class="nav-item active"><a class="nav-link" asp-area="" asp-controller="Acount" asp-action="Login">Zaloguj</a></li>
                    }

                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ContestAdvisor</p>
        </footer>
    </div>

    

    @RenderSection("Scripts", required: false)
    <script src="~/lib/bootstrap/dist/js/jquery-3.4.1.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>